/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminScreeningRouteImport } from './routes/admin/screening'
import { Route as CandidateApplicationsRouteImport } from './routes/candidate/applications'
import { Route as CandidateLoginRouteImport } from './routes/candidate/login'
import { Route as CandidateProfileRouteImport } from './routes/candidate/profile'
import { Route as CandidateRegisterRouteImport } from './routes/candidate/register'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as ScreeningApplicationIdRouteImport } from './routes/screening/$applicationId'
import { Route as ScreeningStageIdRouteImport } from './routes/screening.$stageId'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin/applications/index'
import { Route as AdminApplicationsApplicationIdRouteImport } from './routes/admin/applications/$applicationId'
import { Route as AdminCandidatesIndexRouteImport } from './routes/admin/candidates/index'
import { Route as AdminEmployersIndexRouteImport } from './routes/admin/employers/index'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminJobsJobIdRouteImport } from './routes/admin/jobs/$jobId'
import { Route as AdminJobsCreateRouteImport } from './routes/admin/jobs/create'
import { Route as AdminScreeningApplicationIdRouteImport } from './routes/admin/screening/$applicationId'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as JobsJobIdIndexRouteImport } from './routes/jobs/$jobId/index'
import { Route as JobsJobIdApplyRouteImport } from './routes/jobs/$jobId/apply'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScreeningRoute = AdminScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => AdminRoute,
} as any)
const CandidateApplicationsRoute = CandidateApplicationsRouteImport.update({
  id: '/candidate/applications',
  path: '/candidate/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateLoginRoute = CandidateLoginRouteImport.update({
  id: '/candidate/login',
  path: '/candidate/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRegisterRoute = CandidateRegisterRouteImport.update({
  id: '/candidate/register',
  path: '/candidate/register',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningApplicationIdRoute = ScreeningApplicationIdRouteImport.update({
  id: '/screening/$applicationId',
  path: '/screening/$applicationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningStageIdRoute = ScreeningStageIdRouteImport.update({
  id: '/screening/$stageId',
  path: '/screening/$stageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminApplicationsRoute,
} as any)
const AdminApplicationsApplicationIdRoute =
  AdminApplicationsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AdminApplicationsRoute,
  } as any)
const AdminCandidatesIndexRoute = AdminCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployersIndexRoute = AdminEmployersIndexRouteImport.update({
  id: '/employers/',
  path: '/employers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsJobIdRoute = AdminJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsCreateRoute = AdminJobsCreateRouteImport.update({
  id: '/jobs/create',
  path: '/jobs/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScreeningApplicationIdRoute =
  AdminScreeningApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AdminScreeningRoute,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const JobsJobIdIndexRoute = JobsJobIdIndexRouteImport.update({
  id: '/jobs/$jobId/',
  path: '/jobs/$jobId/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdApplyRoute = JobsJobIdApplyRouteImport.update({
  id: '/jobs/$jobId/apply',
  path: '/jobs/$jobId/apply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/screening': typeof AdminScreeningRouteWithChildren
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/register': typeof CandidateRegisterRoute
  '/screening/$applicationId': typeof ScreeningApplicationIdRoute
  '/screening/$stageId': typeof ScreeningStageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/admin/jobs/create': typeof AdminJobsCreateRoute
  '/admin/screening/$applicationId': typeof AdminScreeningApplicationIdRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/candidates/': typeof AdminCandidatesIndexRoute
  '/admin/employers/': typeof AdminEmployersIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/screening': typeof AdminScreeningRouteWithChildren
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/register': typeof CandidateRegisterRoute
  '/screening/$applicationId': typeof ScreeningApplicationIdRoute
  '/screening/$stageId': typeof ScreeningStageIdRoute
  '/admin': typeof AdminIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/admin/jobs/create': typeof AdminJobsCreateRoute
  '/admin/screening/$applicationId': typeof AdminScreeningApplicationIdRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/candidates': typeof AdminCandidatesIndexRoute
  '/admin/employers': typeof AdminEmployersIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/jobs/$jobId': typeof JobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/screening': typeof AdminScreeningRouteWithChildren
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/login': typeof CandidateLoginRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/register': typeof CandidateRegisterRoute
  '/screening/$applicationId': typeof ScreeningApplicationIdRoute
  '/screening/$stageId': typeof ScreeningStageIdRoute
  '/admin/': typeof AdminIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/applications/$applicationId': typeof AdminApplicationsApplicationIdRoute
  '/admin/jobs/$jobId': typeof AdminJobsJobIdRoute
  '/admin/jobs/create': typeof AdminJobsCreateRoute
  '/admin/screening/$applicationId': typeof AdminScreeningApplicationIdRoute
  '/jobs/$jobId/apply': typeof JobsJobIdApplyRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/candidates/': typeof AdminCandidatesIndexRoute
  '/admin/employers/': typeof AdminEmployersIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/jobs/$jobId/': typeof JobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/account'
    | '/admin/applications'
    | '/admin/profile'
    | '/admin/screening'
    | '/candidate/applications'
    | '/candidate/login'
    | '/candidate/profile'
    | '/candidate/register'
    | '/screening/$applicationId'
    | '/screening/$stageId'
    | '/admin/'
    | '/jobs/'
    | '/admin/applications/$applicationId'
    | '/admin/jobs/$jobId'
    | '/admin/jobs/create'
    | '/admin/screening/$applicationId'
    | '/jobs/$jobId/apply'
    | '/admin/applications/'
    | '/admin/candidates/'
    | '/admin/employers/'
    | '/admin/jobs/'
    | '/admin/users/'
    | '/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/account'
    | '/admin/profile'
    | '/admin/screening'
    | '/candidate/applications'
    | '/candidate/login'
    | '/candidate/profile'
    | '/candidate/register'
    | '/screening/$applicationId'
    | '/screening/$stageId'
    | '/admin'
    | '/jobs'
    | '/admin/applications/$applicationId'
    | '/admin/jobs/$jobId'
    | '/admin/jobs/create'
    | '/admin/screening/$applicationId'
    | '/jobs/$jobId/apply'
    | '/admin/applications'
    | '/admin/candidates'
    | '/admin/employers'
    | '/admin/jobs'
    | '/admin/users'
    | '/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/account'
    | '/admin/applications'
    | '/admin/profile'
    | '/admin/screening'
    | '/candidate/applications'
    | '/candidate/login'
    | '/candidate/profile'
    | '/candidate/register'
    | '/screening/$applicationId'
    | '/screening/$stageId'
    | '/admin/'
    | '/jobs/'
    | '/admin/applications/$applicationId'
    | '/admin/jobs/$jobId'
    | '/admin/jobs/create'
    | '/admin/screening/$applicationId'
    | '/jobs/$jobId/apply'
    | '/admin/applications/'
    | '/admin/candidates/'
    | '/admin/employers/'
    | '/admin/jobs/'
    | '/admin/users/'
    | '/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CandidateApplicationsRoute: typeof CandidateApplicationsRoute
  CandidateLoginRoute: typeof CandidateLoginRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateRegisterRoute: typeof CandidateRegisterRoute
  ScreeningApplicationIdRoute: typeof ScreeningApplicationIdRoute
  ScreeningStageIdRoute: typeof ScreeningStageIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
  JobsJobIdApplyRoute: typeof JobsJobIdApplyRoute
  JobsJobIdIndexRoute: typeof JobsJobIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/screening': {
      id: '/admin/screening'
      path: '/screening'
      fullPath: '/admin/screening'
      preLoaderRoute: typeof AdminScreeningRouteImport
      parentRoute: typeof AdminRoute
    }
    '/candidate/applications': {
      id: '/candidate/applications'
      path: '/candidate/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof CandidateApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/login': {
      id: '/candidate/login'
      path: '/candidate/login'
      fullPath: '/candidate/login'
      preLoaderRoute: typeof CandidateLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/register': {
      id: '/candidate/register'
      path: '/candidate/register'
      fullPath: '/candidate/register'
      preLoaderRoute: typeof CandidateRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/$applicationId': {
      id: '/screening/$applicationId'
      path: '/screening/$applicationId'
      fullPath: '/screening/$applicationId'
      preLoaderRoute: typeof ScreeningApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening/$stageId': {
      id: '/screening/$stageId'
      path: '/screening/$stageId'
      fullPath: '/screening/$stageId'
      preLoaderRoute: typeof ScreeningStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof AdminApplicationsRoute
    }
    '/admin/applications/$applicationId': {
      id: '/admin/applications/$applicationId'
      path: '/$applicationId'
      fullPath: '/admin/applications/$applicationId'
      preLoaderRoute: typeof AdminApplicationsApplicationIdRouteImport
      parentRoute: typeof AdminApplicationsRoute
    }
    '/admin/candidates/': {
      id: '/admin/candidates/'
      path: '/candidates'
      fullPath: '/admin/candidates/'
      preLoaderRoute: typeof AdminCandidatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employers/': {
      id: '/admin/employers/'
      path: '/employers'
      fullPath: '/admin/employers/'
      preLoaderRoute: typeof AdminEmployersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/$jobId': {
      id: '/admin/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/admin/jobs/$jobId'
      preLoaderRoute: typeof AdminJobsJobIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/create': {
      id: '/admin/jobs/create'
      path: '/jobs/create'
      fullPath: '/admin/jobs/create'
      preLoaderRoute: typeof AdminJobsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/screening/$applicationId': {
      id: '/admin/screening/$applicationId'
      path: '/$applicationId'
      fullPath: '/admin/screening/$applicationId'
      preLoaderRoute: typeof AdminScreeningApplicationIdRouteImport
      parentRoute: typeof AdminScreeningRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/jobs/$jobId/': {
      id: '/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof JobsJobIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/apply': {
      id: '/jobs/$jobId/apply'
      path: '/jobs/$jobId/apply'
      fullPath: '/jobs/$jobId/apply'
      preLoaderRoute: typeof JobsJobIdApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminApplicationsRouteChildren {
  AdminApplicationsApplicationIdRoute: typeof AdminApplicationsApplicationIdRoute
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
}

const AdminApplicationsRouteChildren: AdminApplicationsRouteChildren = {
  AdminApplicationsApplicationIdRoute: AdminApplicationsApplicationIdRoute,
  AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
}

const AdminApplicationsRouteWithChildren =
  AdminApplicationsRoute._addFileChildren(AdminApplicationsRouteChildren)

interface AdminScreeningRouteChildren {
  AdminScreeningApplicationIdRoute: typeof AdminScreeningApplicationIdRoute
}

const AdminScreeningRouteChildren: AdminScreeningRouteChildren = {
  AdminScreeningApplicationIdRoute: AdminScreeningApplicationIdRoute,
}

const AdminScreeningRouteWithChildren = AdminScreeningRoute._addFileChildren(
  AdminScreeningRouteChildren,
)

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminApplicationsRoute: typeof AdminApplicationsRouteWithChildren
  AdminProfileRoute: typeof AdminProfileRoute
  AdminScreeningRoute: typeof AdminScreeningRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminJobsJobIdRoute: typeof AdminJobsJobIdRoute
  AdminJobsCreateRoute: typeof AdminJobsCreateRoute
  AdminCandidatesIndexRoute: typeof AdminCandidatesIndexRoute
  AdminEmployersIndexRoute: typeof AdminEmployersIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminApplicationsRoute: AdminApplicationsRouteWithChildren,
  AdminProfileRoute: AdminProfileRoute,
  AdminScreeningRoute: AdminScreeningRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminJobsJobIdRoute: AdminJobsJobIdRoute,
  AdminJobsCreateRoute: AdminJobsCreateRoute,
  AdminCandidatesIndexRoute: AdminCandidatesIndexRoute,
  AdminEmployersIndexRoute: AdminEmployersIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CandidateApplicationsRoute: CandidateApplicationsRoute,
  CandidateLoginRoute: CandidateLoginRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateRegisterRoute: CandidateRegisterRoute,
  ScreeningApplicationIdRoute: ScreeningApplicationIdRoute,
  ScreeningStageIdRoute: ScreeningStageIdRoute,
  JobsIndexRoute: JobsIndexRoute,
  JobsJobIdApplyRoute: JobsJobIdApplyRoute,
  JobsJobIdIndexRoute: JobsJobIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
